#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
安心智能助手 · Plugin → Backend 单向同步

从 .claude-plugin/marketplace.json + plugins/<persona>/.claude-plugin/plugin.json
自动生成：

  backend/src/agents/personas/_plugin_index.py   ← 不要手改

后端 PersonaRegistry 在 autoload() 时会 import 这个文件，把 plugin 元数据（slash 命令、
skill 列表、关联 cookbook、CLAUDE.md 路径）暴露给 /api/personas API，让前端工作台
不需要在两处维护信息。

用法：
  python3 scripts/sync-plugins-to-backend.py            # 全量同步
  python3 scripts/sync-plugins-to-backend.py --check    # 只校验是否已是最新

参考 Anthropic claude-for-financial-services 的 sync-agent-skills.py。
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"
OUT = ROOT / "backend" / "src" / "agents" / "personas" / "_plugin_index.py"


HEADER = '''# -*- coding: utf-8 -*-
# AUTOGENERATED — DO NOT EDIT BY HAND
# Source: .claude-plugin/marketplace.json + plugins/*/.claude-plugin/plugin.json
# Regenerate: python3 scripts/sync-plugins-to-backend.py
# Generated at: {ts}

"""Plugin index — single source of truth for /api/personas to merge with PersonaRegistry."""

from __future__ import annotations

from typing import Final

PLUGIN_INDEX: Final[dict[str, dict]] = '''


def collect() -> dict:
    marketplace = json.loads(MARKETPLACE.read_text(encoding="utf-8"))
    index: dict[str, dict] = {}
    for entry in marketplace.get("plugins", []):
        pdir = ROOT / entry["path"]
        pj = pdir / ".claude-plugin" / "plugin.json"
        if not pj.exists():
            print(f"⚠ 缺 plugin.json: {entry['path']}", file=sys.stderr)
            continue
        meta = json.loads(pj.read_text(encoding="utf-8"))
        # SKILL.md 现场扫描，以本地为准（plugin.json 里的 skills 字段只是声明）
        skills = []
        for sk in sorted(pdir.glob("skills/*/SKILL.md")):
            name = sk.parent.name
            skills.append({
                "name": name,
                "slash": f"/{entry['name']}:{name}",
                "path": str(sk.relative_to(ROOT)),
            })
        agents = []
        for ag in sorted(pdir.glob("agents/*.md")):
            agents.append({
                "name": ag.stem,
                "path": str(ag.relative_to(ROOT)),
            })
        index[entry["name"]] = {
            "displayName": entry.get("displayName") or meta.get("displayName"),
            "description": entry.get("description") or meta.get("description"),
            "category": entry.get("category") or meta.get("category"),
            "domain": meta.get("domain"),
            "requiresColdStart": meta.get("requiresColdStart", True),
            "practiceProfile": str((pdir / meta.get("practiceProfile", "CLAUDE.md")).relative_to(ROOT)),
            "skills": skills,
            "managedAgents": agents,
            "pluginPath": entry["path"],
            "tags": entry.get("tags", []),
        }
    return index


def render(index: dict) -> str:
    import pprint
    body = pprint.pformat(index, indent=4, width=120, sort_dicts=False)
    return (
        HEADER.format(ts=dt.datetime.utcnow().isoformat() + "Z")
        + body
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="只校验是否已是最新（CI 用），不写入")
    args = parser.parse_args()

    index = collect()
    new_text = render(index)
    OUT.parent.mkdir(parents=True, exist_ok=True)

    def _strip_ts(s: str) -> str:
        # 忽略 "# Generated at: ..." 这一行的时间差，便于 CI --check
        return "\n".join(
            ln for ln in s.splitlines() if not ln.startswith("# Generated at:")
        )

    if args.check:
        if OUT.exists() and _strip_ts(OUT.read_text(encoding="utf-8")) == _strip_ts(new_text):
            print("✅ backend/_plugin_index.py 已是最新")
            return 0
        print("✗ backend/_plugin_index.py 已过期，请跑 python3 scripts/sync-plugins-to-backend.py", file=sys.stderr)
        return 1

    OUT.write_text(new_text, encoding="utf-8")
    print(f"✅ 写入 {OUT.relative_to(ROOT)}（{len(index)} personas）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
